server:
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    username: pustygina.nastya@gmail.com
    password: ixui veia alup ezmf
    port: 587
    protocol: smtp
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
  liquibase:
    user: roots_admin
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/roots
    username: roots_admin
    password: roots_password
    driver-class-name: org.postgresql.Driver
    jpa:
      showsql: true
      database: postgresql
      generate-ddl: false
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        ddl-auto: none